services:
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=pokemonbattle'
      - 'POSTGRES_PASSWORD=mypass123'
      - 'POSTGRES_USER=rahul'
    ports:
      - '5432:5432'
  redisjson:
    image: "redislabs/rejson:latest"
    container_name: redis-json
    ports:
      - "6379:6379"
