# Application Configuration
spring.application.name=pokemonbattlebackend

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

# Custom Redis JSON Configuration
redis-json.host=${REDIS_JSON_HOST}
redis-json.port=${REDIS_JSON_PORT}
redis-json.password=${REDIS_JSON_PASSWORD}

# Socket Server Configuration
socket-server.port=${SOCKET_SERVER_PORT}
socket-server.host=${SOCKET_SERVER_HOST}

# Security Configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration